name: Deploy
on:
  push:
    branches:
      - github_actions_test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.14.0]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # 1. 現在のブランチ名を取得
    - id: extract-branch
      name: Extract branch name
      run: echo "::set-output name=BRANCH_NAME::${GITHUB_REF#refs/heads/}"

    # 2. デプロイ用の環境変数を設定
    - name: Set env values for deploy
      if: steps.extract-branch.outputs.BRANCH_NAME == 'github_actions_test'
      run: |
        echo "TARGET=stg" >> $GITHUB_ENV
        echo "S3=hoge" >> $GITHUB_ENV
        echo "CF=fuga" >> $GITHUB_ENV

    - name: Set env values for deploy
      if: steps.extract-branch.outputs.BRANCH_NAME == 'main'
      run: |
        echo "TARGET=prod" >> $GITHUB_ENV
        echo "S3=hogehoge" >> $GITHUB_ENV
        echo "CF=fugafuga" >> $GITHUB_ENV

    # 4. 環境変数を確認
    - name: Check env values
      env:
        HOGEFUGA: ${{ hoge-$TARGET-fuga }}
      run: |
        echo $TARGET
        echo $S3
        echo $CF
        echo $HOGEFUGA
